<?php

namespace FindMeBundle\Repository;

/**
 * ImageSendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSendRepository extends \Doctrine\ORM\EntityRepository
{
}
