imagesend_index:
    path:     /
    defaults: { _controller: "FindMeBundle:ImageSend:index" }
    methods:  GET

imagesend_show:
    path:     /{id}/show
    defaults: { _controller: "FindMeBundle:ImageSend:show" }
    methods:  GET

imagesend_new:
    path:     /new
    defaults: { _controller: "FindMeBundle:ImageSend:new" }
    methods:  [GET, POST]

imagesend_edit:
    path:     /{id}/edit
    defaults: { _controller: "FindMeBundle:ImageSend:edit" }
    methods:  [GET, POST]

imagesend_delete:
    path:     /{id}/delete
    defaults: { _controller: "FindMeBundle:ImageSend:delete" }
    methods:  DELETE
