FindMeBundle\Entity\Game:
    type: entity
    table: null
    repositoryClass: FindMeBundle\Repository\GameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        photo:
            type: text
        indice:
            type: string
            length: 255

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]

    manyToOne:
        winner:
            targetEntity: User
            inversedBy: winners
        author:
            targetEntity: User
            inversedBy: authors
        level:
            targetEntity: Level
            inversedBy: levels
    manyToMany:
        users:
            targetEntity: User
            mappedBy: games
