FindMeBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: FindMeBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        points:
            type: integer
            nullable: true

    lifecycleCallbacks: {  }

    oneToMany:
        winners:
            targetEntity: Game
            mappedBy: winner
        authors:
            targetEntity: Game
            mappedBy: author

    manyToMany:
        clusters:
            targetEntity: Cluster
            inversedBy: users
            joinTable:
                name: users_clusters
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    cluster_id:
                        referencedColumnName: id